services:
  backend:
    build: ../backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  fastapi_service:
    build: ../fastapi_service
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notestream
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
